INSERT INTO SUBJECT(subjName)
SELECT DISTINCT ukrtest
FROM ZNODATA
WHERE ukrtest IS NOT NULL;

INSERT INTO SUBJECT(subjName)
SELECT DISTINCT histtest
FROM ZNODATA
WHERE histtest IS NOT NULL;

INSERT INTO SUBJECT(subjName)
SELECT DISTINCT mathtest
FROM ZNODATA
WHERE mathtest IS NOT NULL;

INSERT INTO SUBJECT(subjName)
SELECT DISTINCT phystest
FROM ZNODATA
WHERE phystest IS NOT NULL;

INSERT INTO SUBJECT(subjName)
SELECT DISTINCT chemtest
FROM ZNODATA
WHERE chemtest IS NOT NULL;

INSERT INTO SUBJECT(subjName)
SELECT DISTINCT biotest
FROM ZNODATA
WHERE biotest IS NOT NULL;

INSERT INTO SUBJECT(subjName)
SELECT DISTINCT geotest
FROM ZNODATA
WHERE geotest IS NOT NULL;

INSERT INTO SUBJECT(subjName)
SELECT DISTINCT engtest
FROM ZNODATA
WHERE engtest IS NOT NULL;

INSERT INTO SUBJECT(subjName)
SELECT DISTINCT fratest
FROM ZNODATA
WHERE fratest IS NOT NULL;

INSERT INTO SUBJECT(subjName)
SELECT DISTINCT deutest
FROM ZNODATA
WHERE deutest IS NOT NULL;

INSERT INTO SUBJECT(subjName)
SELECT DISTINCT spatest
FROM ZNODATA
WHERE spatest IS NOT NULL;


INSERT INTO EDUINSTITUTIONPARENT(EOParent)
SELECT DISTINCT EOParent
FROM ZNODATA
WHERE EOParent IS NOT NULL;


INSERT INTO GEOLOCATION(RegName, AreaName, TerName)
SELECT DISTINCT REGNAME, AREANAME, TERNAME
FROM ZNODATA;


INSERT INTO STUDENT(outid, terId, birth, sex)
SELECT zd.outid, gl.terId, zd.birth, zd.sextypename
FROM ZNODATA zd
LEFT JOIN GEOLOCATION gl
ON zd.areaname = gl.areaname AND zd.regname = gl.regname AND zd.tername = gl.tername;


INSERT INTO ZNOINSTITUTION(PTName, terId)
SELECT DISTINCT zd.EONAME, gl.terId
FROM ZNODATA zd
LEFT JOIN GEOLOCATION gl
ON zd.EORegName = gl.regname AND zd.EOTerName = gl.regname AND zd.EOAreaName = gl.areaname
WHERE zd.EONAME IS NOT NULL;


INSERT INTO EDUINSTITUTION(terId, EOParent, EOName, EOTypeName)
SELECT DISTINCT gl.terId, zd.EOParent, zd.EONAME, zd.EOTYPENAME
FROM ZNODATA zd
LEFT JOIN GEOLOCATION gl
ON zd.EORegName = gl.regname AND zd.EOTerName = gl.regname AND zd.EOAreaName = gl.areaname
WHERE zd.EONAME IS NOT NULL;


INSERT INTO 
